- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.00001
    batch_size: 64
    epochs: 512
    loss: mse
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: true

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.00001
    batch_size: 64
    epochs: 512
    loss: mse
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: false

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.0001
    batch_size: 64
    epochs: 512
    loss: mse
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: true

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.00001
    batch_size: 64
    epochs: 512
    loss: mse
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: true

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.0001
    batch_size: 64
    epochs: 512
    loss: mae
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: false

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.00001
    batch_size: 64
    epochs: 512
    loss: mae
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: false

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.0001
    batch_size: 64
    epochs: 512
    loss: mae
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: true

- hyperparameters:
    window_in: 30
    window_out: 1
    optimizer: Adam
    learning_rate: 0.00001
    batch_size: 64
    epochs: 512
    loss: mae
  missing_value_strategy: "MEAN"
  remove_unknown_train_values: false
  remove_unknown_test_values: true

